// Shared by the PDF/DOCX exporters and the report editor UI — kept in its
// own file (not generateDocxReport.ts) so the client bundle doesn't pull in
// the `docx` package just to read this one string.
export const AI_COMPARATIVE_ANALYSIS_DISCLAIMER =
  "This analysis was generated by AI. AI can make mistakes, so please review it before finalizing the report.";
