import type { CategoryName, RankVendorComparisonResult, VendorRanking } from "./rankVendorComparison";

export function ordinal(n: number): string {
  const remainder100 = n % 100;
  if (remainder100 >= 11 && remainder100 <= 13) return `${n}th`;
  switch (n % 10) {
    case 1:
      return `${n}st`;
    case 2:
      return `${n}nd`;
    case 3:
      return `${n}rd`;
    default:
      return `${n}th`;
  }
}

function joinNames(names: string[]): string {
  if (names.length === 1) return names[0];
  if (names.length === 2) return `${names[0]} and ${names[1]}`;
  return `${names.slice(0, -1).join(", ")}, and ${names[names.length - 1]}`;
}

// This is the code-authored statement of the ranking itself — the one
// sentence in each subsection that is never AI-generated, so the "no vendor
// is described as leading unless it actually is, ties are described as
// ties, not-enough-data vendors are never given a rank" requirements hold
// by construction, not by validating free text after the fact.
function formatOneRanking(
  entries: { vendorId: number; ranking: VendorRanking }[],
  vendorNames: Map<number, string>
): string {
  const nameFor = (id: number) => vendorNames.get(id) ?? `Vendor ${id}`;

  const ranked = entries.filter(
    (entry): entry is { vendorId: number; ranking: Extract<VendorRanking, { status: "ranked" }> } =>
      entry.ranking.status === "ranked"
  );
  const notEnoughData = entries.filter((entry) => entry.ranking.status === "not-enough-data");

  const idsByRank = new Map<number, number[]>();
  for (const entry of ranked) {
    const ids = idsByRank.get(entry.ranking.rank) ?? [];
    ids.push(entry.vendorId);
    idsByRank.set(entry.ranking.rank, ids);
  }

  const rankSentences = Array.from(idsByRank.entries())
    .sort(([rankA], [rankB]) => rankA - rankB)
    .map(([rank, ids]) => {
      const names = joinNames(ids.map(nameFor));
      const verb = ids.length > 1 ? "are tied for" : "ranks";
      return `${names} ${verb} ${ordinal(rank)}`;
    });

  const notEnoughSentence =
    notEnoughData.length > 0
      ? `${joinNames(notEnoughData.map((entry) => nameFor(entry.vendorId)))} ${
          notEnoughData.length > 1 ? "do" : "does"
        } not have enough data for this`
      : null;

  const parts = [...rankSentences, ...(notEnoughSentence ? [notEnoughSentence] : [])];
  if (parts.length === 0) {
    return "There is not enough data to compare vendors here.";
  }
  return `${parts.join("; ")}.`;
}

export interface VendorComparisonSummaries {
  overall: string;
  delivery: string;
  pricing: string;
  orderAccuracy: string;
}

/**
 * Formats the four code-authored ranking-statement sentences (one per
 * subsection) from a computed RankVendorComparisonResult. These are
 * prepended to the AI's explanatory text, never generated by the AI.
 */
export function formatVendorComparisonSummaries(
  comparison: RankVendorComparisonResult,
  vendorNames: Map<number, string>
): VendorComparisonSummaries {
  const forCategory = (category: CategoryName) =>
    formatOneRanking(
      comparison.vendors.map((vendor) => ({ vendorId: vendor.vendorId, ranking: vendor.categories[category] })),
      vendorNames
    );

  return {
    overall: formatOneRanking(
      comparison.vendors.map((vendor) => ({ vendorId: vendor.vendorId, ranking: vendor.overall })),
      vendorNames
    ),
    delivery: forCategory("delivery"),
    pricing: forCategory("pricing"),
    orderAccuracy: forCategory("orderAccuracy"),
  };
}
