import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import MsalProviderWrapper from "@/components/auth/MsalProviderWrapper";
import AppShell from "@/components/layout/AppShell";

const inter = Inter({
  variable: "--font-sans-custom",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vendor Performance Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MsalProviderWrapper>
          <AppShell>{children}</AppShell>
        </MsalProviderWrapper>
      </body>
    </html>
  );
}
